---

- name: system-dependant vars if any
  include_vars: '{{ lookup("first_found", params) }}'
  vars:
    params:
      files:
        - '{{ ansible_os_family }}-{{ ansible_distribution_major_version | default(ansible_distribution_version) }}.yml'
        - '{{ ansible_os_family }}.yml'
        - '{{ ansible_distribution }}.yml'
        - main.yml
      paths:
        - vars
      skip: True
  tags: munin,vars

- name: munin node
  include_tasks: node.yml
  when: munin_host | length > 0
  tags: munin-node,vars

- name: munin master
  include_tasks: master.yml
  when: munin_host == inventory_hostname and munin_role == 'master'
  #or ( munin_host not in ansible_play_batch and munin_aggr_templates | count > 0 )
  tags: munin-master,vars
