---
- name: enable default plugins
  shell: 'set -o pipefail
  munin-node-configure --shell | fgrep -v plugins/if_ | fgrep -v plugins/sendmail_ | sh'
  args:
    creates: '{{ munin_etcdir }}/plugins/load'
  notify:
    - restart munin node
    - restart munin asyncd

- name: snmp plugin
  file:
    src: '{{ munin_dist_plugins }}/snmp__if_multi'
    dest: '{{ munin_etcdir }}/plugins/snmp_localhost_if_multi'
    state: link
  when: not ansible_virtualization_type == "jails"
  notify:
    - restart munin node
    - restart munin asyncd

- name: additional plugins
  file:
    src: '{{ item | regex_replace(" .*$","") | regex_replace("^([^/])",munin_dist_plugins+"/\1") }}'
    dest: '{{ munin_etcdir }}/plugins/{% if item|regex_search(" ") %}{{ item | regex_replace(".* ","") }}{% else %}{{ item | basename }}{% endif %}'
    state: link
  with_items: '{{ munin_plugins }}'
  notify:
    - restart munin node
    - restart munin asyncd

- name: munin config blobs
  copy:
    dest: '{{ munin_etcdir }}/plugin-conf.d/{{ item.key }}'
    content: '{{ item.value }}'
  with_dict: '{{ munin_configs }}'
  notify:
    - restart munin node
    - restart munin asyncd

- name: munin config files
  copy:
    dest: '{{ munin_etcdir }}/plugin-conf.d/{{ item | basename }}'
    src: '{{ item }}'
  with_items: '{{ munin_config_files }}'
  notify:
    - restart munin node
    - restart munin asyncd
