---
# handlers file for criecm.munin
- name: restart munin node
  service:
    name: '{{ munin_service }}'
    state: restarted

- name: restart munin asyncd
  service:
    name: '{{ munin_asyncd_service }}'
    state: restarted
  ignore_errors: yes
