---
# handlers file for criecm.munin
- name: restart munin node
  service:
    name: '{{ munin_service }}'
    state: restarted
  ignore_errors: "{{ ansible_check_mode }}"

- name: restart munin asyncd
  service:
    name: '{{ munin_asyncd_service }}'
    state: started
  ignore_errors: yes
